on:
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14, 16]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node }}
    - run: npm ci && npm run build && rm -rf node_modules
    - run: mv ./cloudwatch-nodejs-plugin/cloudwatch-nodejs-plugin.node ./cloudwatch-nodejs-plugin/cloudwatch-nodejs-plugin.linux-x64-node${{ matrix.node }}
    - uses: uraimo/run-on-arch-action@v2
      name: Build on ARM64
      id: runcmd
      with:
        arch: aarch64
        distro: ubuntu22.04
        dockerRunArgs: |
          --volume "${PWD}:/app"

        # Set an output parameter `uname` for use in subsequent steps
        install: |
          apt-get update
          apt-get install curl sudo build-essential
          curl -fsSL https://deb.nodesource.com/setup_${{ matrix.node }}.x | sudo -E bash -
          apt-get install -y nodejs
        run: |
          cd /app
          npm ci
          npm run build
          rm -rf node_modules
          mv ./cloudwatch-nodejs-plugin/cloudwatch-nodejs-plugin.node ./cloudwatch-nodejs-plugin/cloudwatch-nodejs-plugin.linux-arm64-node${{ matrix.node }}
    - uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.node }}-${{ matrix.arch }}
        path: ./cloudwatch-nodejs-plugin