on:
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14, 16]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node }}
    - run: npm ci && npm run build && rm -rf node_modules
    - run: mv ./cloudwatch-nodejs-plugin/cloudwatch-nodejs-plugin.node ./cloudwatch-nodejs-plugin/cloudwatch-nodejs-plugin.linux-x64-node${{ matrix.node }}
    - uses: uraimo/run-on-arch-action@v2
      name: Build on ARM64
      with:
        arch: aarch64
        distro: ubuntu22.04
        dockerRunArgs: |
          --volume "${PWD}:/app"

        # Set an output parameter `uname` for use in subsequent steps
        install: |
          apt-get update && apt-get install -y curl
          curl -fsSL https://deb.nodesource.com/setup_${{ matrix.node }}.x | -E bash -
          apt-get install -y nodejs build-essential
        run: |
          cd /app
          npm ci
          npm run build
          rm -rf node_modules
          mv ./cloudwatch-nodejs-plugin/cloudwatch-nodejs-plugin.node ./cloudwatch-nodejs-plugin/cloudwatch-nodejs-plugin.linux-arm64-node${{ matrix.node }}
    - run: zip --junk-paths artifact.zip cloudwatch-nodejs-plugin/*
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./artifact.zip
        asset_name: cloudwatch-nodejs-plugin-node${{ matrix.node }}.zip
        asset_content_type: application/zip